### ISSUE TITLE
Controller Class

### ISSUE THREAD

**Issue by pcgeek2301** [cobracommanders/FRC-2019-Robot#2]
The Controller Class code should handle the following: 

- implementing the joystick and joystick button provided by first 

- implement the logic for the button mappings by mapping to the button ids for the xbox controller 

-  implement the joystick axis class to be able to create the triggers on the back of the controller and the two joysticks as buttons that can be controlled. 

Notes: 
- The joysticks on the controller has 2 axes for x and y.

**Comment by bandgeek2031** [comment]
I worked with Kirshe and made the controller class.

**Comment by pcgeek2301** [comment]
I worked with Kirshe and made the controller class.
