### ISSUE TITLE
Remove custom lib dependencies and replace with WPI vendordeps

### ISSUE THREAD

**Issue by imapcgeek** [cobracommanders/FRC-2019-Robot#24]
* Remove flatDir repo from build.gradle
* Remove compile directives for compile 'com.ctre.phoenix:wpiapi-java:5.12.1' and compile 'com.ctre.phoenix:api-java:5.12.1'
* Use WPI Manage Vendor Libraries command (in VS Code) to add vendor dependencies from this url '    "http://devsite.ctr-electronics.com/maven/release/com/ctre/phoenix/Phoenix-latest.json"
* Verify that the project still builds with the TalonSRX dependencies in place

**Comment by pcgeek2301** [comment]
All works and is good to go! 👍
