### ISSUE TITLE
Clamp Subsystem 

### ISSUE THREAD

**Issue by pcgeek2301** [cobracommanders/FRC-2019-Robot#8]
The Clamp Subsystem code should handle the following: 
- implement double solenoid
- create a set clamps method 

Notes:
- The set clamps method is going to need a if/else statement.
- the parameters is going to use a boolean

**Comment by RandyyPham** [comment]
ON IT 👍

**Comment by RandyyPham** [comment]
woohoo we did it

**Comment by pcgeek2301** [comment]
Randy and I completed this, all thats left is the forward and reverse channel for the double solenoid
